name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: |
          nohup npm start &

      - name: Wair for server to start
        run: npx wait-on http://localhost:3000

      - name: Run Jest tests
        run: npm test

      - name: Run Cypress tests
        run: npx cypress run
