name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Super-Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT: true
        VALIDATE_JSON: true
        VALIDATE_MARKDOWN: true
        VALIDATE_YAML: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
